name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn --frozen-lockfile
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn --frozen-lockfile
    - run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn --frozen-lockfile
    - run: yarn build